name: Generate Badges

on:
  push:
    branches: [main]

jobs:
  generate-badges:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        badge:
          - name: build
            label: build
            status: passing
            color: green
            logo: github
          - name: version
            label: version
            status: ${{ github.ref_name }}
            color: blue
            logo: github
          - name: license
            label: license
            status: MIT
            color: green
            logo: github
          - name: coverage
            label: coverage
            status: 95%
            color: brightgreen
            logo: codecov
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create badges directory
        run: |
          mkdir -p badges
          echo "Created badges directory"

      - name: Generate ${{ matrix.badge.name }} Badge
        uses: ./
        with:
          label: ${{ matrix.badge.label }}
          status: ${{ matrix.badge.status }}
          path: badges/${{ matrix.badge.name }}.svg
          color: ${{ matrix.badge.color }}
          style: flat-square
          logo: ${{ matrix.badge.logo }}
          logo-color: white
          commit-message: 🔄 Update ${{ matrix.badge.name }} badge
