name: Generate Badges

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      badge_type:
        description: 'Type of badge to generate'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - build
          - version
          - coverage
          - license

jobs:
  generate-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create badges directory
        run: |
          mkdir -p badges
          echo "Created badges directory"

      - name: Generate Build Badge
        if: ${{ github.event.inputs.badge_type == 'all' || github.event.inputs.badge_type == 'build' }}
        uses: ./
        with:
          label: 'build'
          status: 'passing'
          path: 'badges/build.svg'
          color: 'green'
          style: 'flat-square'
          logo: 'github'
          logo-color: 'white'
          commit-message: '🔄 Update build status badge'

      - name: Generate Version Badge
        if: ${{ github.event.inputs.badge_type == 'all' || github.event.inputs.badge_type == 'version' }}
        uses: ./
        with:
          label: 'version'
          status: ${{ github.ref_name }}
          path: 'badges/version.svg'
          color: 'blue'
          style: 'flat-square'
          logo: 'github'
          logo-color: 'white'
          commit-message: '🔄 Update version badge'

      - name: Generate License Badge
        if: ${{ github.event.inputs.badge_type == 'all' || github.event.inputs.badge_type == 'license' }}
        uses: ./
        with:
          label: 'license'
          status: 'MIT'
          path: 'badges/license.svg'
          color: 'green'
          style: 'flat-square'
          logo: 'github'
          logo-color: 'white'
          commit-message: '🔄 Update license badge'

      - name: Generate Coverage Badge
        if: ${{ github.event.inputs.badge_type == 'all' || github.event.inputs.badge_type == 'coverage' }}
        uses: ./
        with:
          label: 'coverage'
          status: '95%'
          path: 'badges/coverage.svg'
          color: 'brightgreen'
          style: 'flat-square'
          logo: 'codecov'
          logo-color: 'white'
          commit-message: '🔄 Update coverage badge'

      - name: Upload Badges
        uses: actions/upload-artifact@v4
        with:
          name: generated-badges
          path: badges/*.svg
          retention-days: 7
