name: Generate Badges

on:
  push:
    branches: [main]

jobs:
  generate-badges:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - label: build
            status: passing
            file: build.svg
            color: green
            logo: github
          - label: version
            status: ${{ github.ref_name }}
            file: version.svg
            color: blue
            logo: github
          - label: license
            status: MIT
            file: license.svg
            color: green
            logo: github
          - label: coverage
            status: 95%
            file: coverage.svg
            color: brightgreen
            logo: codecov
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create badges directory
        run: mkdir -p badges

      - name: Generate ${{ matrix.label }} Badge
        uses: ./
        with:
          label: ${{ matrix.label }}
          status: ${{ matrix.status }}
          path: badges/${{ matrix.file }}
          color: ${{ matrix.color }}
          style: flat-square
          logo: ${{ matrix.logo }}
          logo-color: white
          commit-message: 🔄 Update ${{ matrix.label }} badge
